{ config, pkgs, ... }:

# Qt/KDE application appearance. Dolphin, Kate and Ark are Qt, and Qt reads none
# of the GTK configuration in ./gtk.nix — so on a desktop that is not Plasma
# they were falling back to whatever their defaults are, which is why Dolphin's
# icons looked wrong. What was actually on screen there was Breeze, not the
# Papirus set configured for GTK.
#
# Before this file, four things were missing at once:
#   - qt6ct / qt5ct were not installed
#   - QT_QPA_PLATFORMTHEME was unset, so nothing told Qt to consult them
#   - neither qt6ct.conf nor qt5ct.conf existed
#   - ~/.config/kdeglobals was a leftover from the Plasma removal with no
#     [Icons] section at all
#
# There is a second reason to fix this beyond appearances. ../noctalia.nix has
# had the `qt` theme template enabled since the terminal work, and it has been
# writing a full colour scheme to qt6ct/colors/noctalia.conf that nothing read.
# Pointing color_scheme_path at that file is what finally connects it.
{
  # Only the settings files live here. The platform theme itself — the plugins
  # and QT_QPA_PLATFORMTHEME — is set in ./configuration.nix instead, because
  # home-manager puts the plugin in the *user* profile and nixpkgs' Qt wrappers
  # pin QT_PLUGIN_PATH to each application's own closure, so the profile copy is
  # never found. Verified by reading Dolphin's /proc/<pid>/environ: no qt6ct in
  # its plugin path at all.
  #
  # style.name is deliberately not set either: it exports QT_STYLE_OVERRIDE,
  # which wins over the `style` key in the files below and would make one of the
  # two the dead setting.
  qt.enable = true;

  # qt6ct.conf itself. Noctalia owns colors/noctalia.conf inside the same
  # directory and does not touch this file, so there is no collision of the kind
  # documented in ./terminal/kitty.nix.
  qt.qt6ctSettings = {
    Appearance = {
      icon_theme = "Papirus-Dark"; # keep in step with gtk.iconTheme in ./gtk.nix
      style = "Fusion";

      # Generated by Noctalia's `qt` template from the active palette. Without
      # custom_palette the path is ignored.
      custom_palette = true;
      color_scheme_path = "${config.xdg.configHome}/qt6ct/colors/noctalia.conf";

      standard_dialogs = "default";
    };

    Fonts = {
      # Matches gtk.font in ./gtk.nix so Qt and GTK windows agree.
      general = ''"Noto Sans,10,-1,5,400,0,0,0,0,0,0,0,0,0,0,1"'';
      fixed = ''"JetBrainsMono Nerd Font,10,-1,5,400,0,0,0,0,0,0,0,0,0,0,1"'';
    };
  };

  # Qt5 is still used by a few things (filezilla among them), so it gets the
  # same treatment rather than being left on defaults.
  qt.qt5ctSettings = {
    Appearance = {
      icon_theme = "Papirus-Dark";
      style = "Fusion";
      custom_palette = true;
      color_scheme_path = "${config.xdg.configHome}/qt5ct/colors/noctalia.conf";
      standard_dialogs = "default";
    };

    Fonts = {
      general = ''"Noto Sans,10,-1,5,50,0,0,0,0,0"'';
      fixed = ''"JetBrainsMono Nerd Font,10,-1,5,50,0,0,0,0,0"'';
    };
  };

  # KDE applications read the icon theme from kdeglobals before falling back to
  # the platform theme, and the file left behind by the Plasma removal has only
  # colour-effect blocks. Stating it here means Dolphin picks up the same icons
  # as everything else instead of Breeze.
  xdg.configFile."kdeglobals".text = ''
    [Icons]
    Theme=Papirus-Dark

    [UiSettings]
    ColorScheme=noctalia
  '';
}
