{ config, pkgs, ... }:

# Qt/KDE application appearance. Dolphin, Kate and Ark are Qt, and Qt reads none
# of the GTK configuration in ./gtk.nix — so on a desktop that is not Plasma
# they were falling back to whatever their defaults are, which is why Dolphin's
# icons looked wrong. What was actually on screen there was Breeze, not the
# Papirus set configured for GTK.
#
# Before this file, four things were missing at once:
#   - qt6ct / qt5ct were not installed
#   - QT_QPA_PLATFORMTHEME was unset, so nothing told Qt to consult them
#   - neither qt6ct.conf nor qt5ct.conf existed
#   - ~/.config/kdeglobals was a leftover from the Plasma removal with no
#     [Icons] section at all
#
# There is a second reason to fix this beyond appearances. DMS's matugen
# templates (matugenTemplateQt5ct/Qt6ct = true in its settings) write a full
# colour scheme to qt{5,6}ct/colors/matugen.conf on every wallpaper change.
# Pointing color_scheme_path at that file is what connects it.
{
  # Only the settings files live here. The platform theme itself — the plugins
  # and QT_QPA_PLATFORMTHEME — is set in ./configuration.nix instead, because
  # home-manager puts the plugin in the *user* profile and nixpkgs' Qt wrappers
  # pin QT_PLUGIN_PATH to each application's own closure, so the profile copy is
  # never found. Verified by reading Dolphin's /proc/<pid>/environ: no qt6ct in
  # its plugin path at all.
  #
  # style.name is deliberately not set either: it exports QT_STYLE_OVERRIDE,
  # which wins over the `style` key in the files below and would make one of the
  # two the dead setting.
  qt.enable = true;

  # qt6ct.conf itself. matugen owns colors/matugen.conf inside the same
  # directory and does not touch this file, so there is no collision.
  qt.qt6ctSettings = {
    Appearance = {
      icon_theme = "Papirus-Dark"; # keep in step with gtk.iconTheme in ./gtk.nix
      style = "Fusion";

      # Generated by DMS's matugen from the active palette. Without
      # custom_palette the path is ignored.
      custom_palette = true;
      color_scheme_path = "${config.xdg.configHome}/qt6ct/colors/matugen.conf";

      standard_dialogs = "default";
    };

    Fonts = {
      # Matches gtk.font in ./gtk.nix so Qt and GTK windows agree.
      general = ''"IBM Plex Sans,10,-1,5,400,0,0,0,0,0,0,0,0,0,0,1"'';
      fixed = ''"JetBrainsMono Nerd Font,10,-1,5,400,0,0,0,0,0,0,0,0,0,0,1"'';
    };
  };

  # Qt5 is still used by a few things (filezilla among them), so it gets the
  # same treatment rather than being left on defaults.
  qt.qt5ctSettings = {
    Appearance = {
      icon_theme = "Papirus-Dark";
      style = "Fusion";
      custom_palette = true;
      color_scheme_path = "${config.xdg.configHome}/qt5ct/colors/matugen.conf";
      standard_dialogs = "default";
    };

    Fonts = {
      general = ''"IBM Plex Sans,10,-1,5,50,0,0,0,0,0"'';
      fixed = ''"JetBrainsMono Nerd Font,10,-1,5,50,0,0,0,0,0"'';
    };
  };

  # KDE applications read the icon theme from kdeglobals before falling back to
  # the platform theme, and the file left behind by the Plasma removal has only
  # colour-effect blocks. Stating it here means Dolphin picks up the same icons
  # as everything else instead of Breeze.
  #
  # [General] TerminalApplication is a second thing this file has to answer for.
  # KTerminalLauncherJob in libKF6KIOGui resolves the terminal by reading
  # TerminalService (a .desktop id) and then TerminalApplication (an executable)
  # from this file's [General] group, with `konsole` hardcoded as the fallback
  # when neither is set. With no Plasma there is no konsole to fall back to, so
  # anything routed through that job died with "Terminal konsole not found":
  # opening a file with a Terminal=true .desktop entry such as nvim's, and
  # Dolphin's own F4. Naming kitty is enough — TerminalApplication is looked up
  # on PATH directly, so unlike TerminalService it does not depend on ksycoca
  # having indexed anything — see the applications.menu note in ./apps.nix for
  # how little is guaranteed to be in the cache on a session without Plasma.
  xdg.configFile."kdeglobals".text = ''
    [General]
    TerminalApplication=kitty

    [Icons]
    Theme=Papirus-Dark

    [UiSettings]
    ColorScheme=matugen
  '';
}
