{
  lib,
  appimageTools,
  fetchurl,
}:

# CurseForge's official Linux client is distributed as an AppImage and is
# officially supported on Ubuntu. Keeping the AppImage inside a Nix package
# makes the install reproducible on NixOS without importing Debian package
# state into the system.
let
  pname = "curseforge";
  version = "1.316.0.37372";

  src = fetchurl {
    url = "https://curseforge.overwolf.com/downloads/curseforge-latest-linux.AppImage";
    hash = "sha256-4DQZNlrJGY1gGAyqB74+vhhI9lCDPAEQrayhSX5G0Uc=";
  };

  contents = appimageTools.extract { inherit pname version src; };
in
appimageTools.wrapType2 {
  inherit pname version src;

  extraInstallCommands = ''
    install -Dm444 ${contents}/curseforge.desktop $out/share/applications/curseforge.desktop

    # The AppImage entry points at its internal AppRun. Replace it with the
    # wrapper generated by appimageTools so the desktop launcher works from
    # the Nix store as well as from a terminal.
    substituteInPlace $out/share/applications/curseforge.desktop \
      --replace-fail 'Exec=AppRun --no-sandbox %U' "Exec=$out/bin/${pname} %U"

    cp -r ${contents}/usr/share/icons $out/share/
  '';

  meta = {
    description = "CurseForge mod manager for Linux";
    homepage = "https://www.curseforge.com/";
    license = lib.licenses.unfree;
    mainProgram = pname;
    platforms = [ "x86_64-linux" ];
    sourceProvenance = with lib.sourceTypes; [ binaryNativeCode ];
  };
}
